### ISSUE TITLE
1.14 Portal Blocks no longer an option for Island Block checks

### ISSUE THREAD

**Issue by Jerethkhan** [BentoBoxWorld/Challenges#139]
### Description
Paper 1.14.2
Nether Portal Blocks and End Portal Blocks do not appear in the GUI when creating challenges that require blocks on an island. 

#### Steps to reproduce the behavior:
Load in any 1.13 challenge that requires nether portal blocks. Upon loading the challenge the block requirement is removed from the requirements.

#### Server / BentoBox information:
Server: Paper 1.14.2 R-0.1
BentoBox: Version 1.5.1
BentoBox Plugins: Biomes 1.5.0.0, BSkyBlock 1.5.0, Challenges 0.7.5, Level 1.5.0, MagicCobblestoneGenerator 1.5.0.1

#### Screenshots / Server log
N/A

#### Expected behavior / Additional context
This is due to portal blocks being removed as obtainable blocks. It will probably need to be set up in the same manner as wall signs and wall heads.

**Comment by BONNe** [comment]
![existingPortalIcon](https://user-images.githubusercontent.com/1344358/59564047-a4e59600-904a-11e9-8d79-900248b382e8.png)
Portals were removed from obtainable blocks in 1.13
The icons for them are papers because I did not know a better way how to indicate it.
By hovering on them you can see the block name.
