### ISSUE TITLE
Challenges - Island Type not working through GUI

### ISSUE THREAD

**Issue by G1lles** [BentoBoxWorld/Challenges#154]
#### Describe the bug

When you want to create a challenge in the GUI and you change the challenge type to Island Type it doesn't do anything when you add a block or an entity
#### Steps to reproduce the behavior

1. /bsb challenges
2. Add new challenge
3. Change challenge type to Island Type
4. Go to requirements
5. Try to add / modify anything, it won't work.
#### Screenshots and videos

/
#### Expected behavior

It should add the specific block or entity
#### Server

 - OS: **Linux*
 - Java version: **8**

#### Plugins

```
Bentobox
```

##### BentoBox and Addons

```
BSkyblock, Challenges, Level
```

##### Configuration

 - Database: **YAML**

**Comment by BONNe** [comment]
I assume you are using Challenges-0.7.5

So, it is working, there is just a mistake from my side. When I created I added ability to select multiple blocks and entities in single click. Unfortunately, I forgot to add ability to select single clicked element.
To get around it, you need to use RIGHT mouse button. You will select element and then with LEFT mouse button, it will return to previous GUI.
It is fixed in snapshot builds.
