### ISSUE TITLE
Import/Export in yml format for MySQL/MariaDB database

### ISSUE THREAD

**Issue by Klaerke91** [BentoBoxWorld/Challenges#202]
#### Is your feature request related to a problem?
Kinda.

Myself and some of my admins dont like that they need to use GUI to edit/create challenges after we change the database to mariadb. 
We use to have the database in yml format where you could edit the yml file
but you cant do that in Mariadb

#### Describe the solution you'd like us to implement.
Be able to Import/Export the challenges in yml format so you can edit it that way instead of the GUI

#### Describe alternatives you've considered.
Cant think of any way to be able to edit in file format when you have a mysql/mariadb database

**Comment by BONNe** [comment]
No, there will be no ability to export or import anything from YAML database. YAML is good for simple structures, but challenges now got a too complex structure to simply export and import. 

However, since 0.7 there already exists functionality to export and import challenges, but it is not perfect and user-friendly. 

It can be done with the command: `/[gamemode_admin] challenges defaults export`
Challenges will be exported in `/plugins/bentobox/addons/challenges/defaults.json` file.
To import them, you can use the command:  `/[gamemode_admin] challenges defaults import`

However, the import is not allowed if there exists any challenge or challenge level. So if you want to import them, you need to remove challenges and levels from a game mode. Since 0.8 there is a TNT button that allows doing that via GUI, but please read the description as one is for removing challenges but another - player data.
