### ISSUE TITLE
Client item names

### ISSUE THREAD

**Issue by OverBrave** [BentoBoxWorld/Challenges#291]
### Is your feature request related to a problem?

It takes a long time to translate.

### Describe the solution you'd like.

Can the names of the items be shaped according to the player's client? So whatever the player's client language is, the names of the items will be shaped accordingly.

(Yes, there is a section in the language file of the last version, but it will take too long to write all the names of the items individually. can't client support be brought directly by the plugin?)

### Describe alternatives you've considered.

Nothing.

### Agreements

- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] I have ensured the feature I'm requesting isn't already in the latest supported BentoBox build or Addons.

**Comment by BONNe** [comment]
To my knowledge, there is no option for the Spigot plugin to get locales file from clients. 

There exist libraries that contain all translations for every block/item/entity. And BentoBox is using one of them:
https://github.com/apachezy/LangUtils

Challenges addon is using BentoBox API for backup-translation, if the custom one is missing, so if you add that plugin, it should translate them.

The reason, why it is not public, because I and Poslovitch did not like how it was implemented, and wanted to rework it. 
However, due to the fact that we do not have time for it, it is left in this "exist" but not "advertised" state.

Challenges will not have any special implementation for it, simply because it does not make sense. There are a lot of add-ons that use items, and using API from BentoBox is more reasonable, than creating a new one for every addon.
